## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [33]:
import numpy as np

# 1. 
vec_a = np.arange(5,11)
vec_b = np.arange(15,21)

# print(vec_a)
# print(vec_b)
# len(vec_a)

# 2.A
vec_c = np.empty((6,6), dtype=np.float32)
# print(vec_c.shape[0], vec_c.shape[1])

for row_index in range(vec_c.shape[0]):
    for col_index in range(vec_c.shape[1]):
        vec_c[row_index, col_index] = vec_a[row_index] * vec_b[col_index]
# print(vec_c)

# 2.B
vec_c_trace = 0
for row_index in range(vec_c.shape[0]):
    vec_c_trace += vec_c[row_index, row_index]
# print(vec_c_trace)


# 3.
vec_d = np.outer(vec_a, vec_b)
print(vec_d)
vec_d_trace = np.trace(vec_d)
print(vec_d_trace)

[[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]
805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [64]:
# 1.A
A = np.random.rand(4,3)
# print(A)
B = np.arange(1,13).reshape(3,4)
# print(B)

C = np.empty((4,4))
for row_index in range(A.shape[0]):
    for col_index in range(B.shape[1]):
        A_row = A[row_index,]
        B_col = B[:,col_index]
#         print(A_row)
#         print(B_col)
        C_val = sum(A_row * B_col)
#         print(C_val)
        C[row_index, col_index] = C_val
# print(C)

# 1.B
C = [sum(A[x,:] * B[:,y]) for x in range(A.shape[0]) for y in range(B.shape[1])]
# C = C.reshape(4,4) # how to make this work?
# print(C)

# 1.C
C = np.matmul(A, B)
print(C)



[[ 7.84077517  9.59912748 11.35747979 13.11583209]
 [12.41896473 15.02972826 17.64049178 20.2512553 ]
 [ 5.52012364  6.55727707  7.5944305   8.63158393]
 [ 7.43425658  8.76132857 10.08840056 11.41547255]]


In [72]:
C_top_rows = C[[0,1]]
print(C_top_rows)
C_ext = C[[0,1]][:,[0,1]]
print(C_ext)

[[ 7.84077517  9.59912748 11.35747979 13.11583209]
 [12.41896473 15.02972826 17.64049178 20.2512553 ]]
[[ 7.84077517  9.59912748]
 [12.41896473 15.02972826]]
